const pianos = [
    {
      id: 1,
      model: "KRAUSS 118",
      color: "Noce",
      colorCode: "#8B4513",
      type: "Verticale",
      condition: "Restaurato",
      productionDate: "1919",
      dimensions: {
        height: "118 cm",
        length: "145 cm",
      },
      price: "5.000",
      description: "I pianoforti KRAUSS vengono costruiti a Spaichingen e la fabbrica, che risale al 1919 ed è una delle più antiche della Germania è ancora pienamente attiva.Come tutte le più importanti case tedesche ha sempre curato la qualità e anche questo modello di 118 cm. di altezza sviluppa una potenza e pienezza di suono per cui lo si scambierebbe per un pianoforte alto almeno quindici cm. in più. La meccanica RENNER conferisce alla tastiera la giusta pesatura e un esemplare controllo del tocco che consente di ottenere una pronta ripetizione.La sonorità è, come già detto, molto potente e ricca di armoniche come solo i pianoforti di grande qualità sanno dare.Naturalmente abbiamo registrato la meccanica e sciolto i movimenti della tastiera che si erano un pò rallentati a causa della lunga inattività e faremo l’ultima accordatura prima della consegna in modo che arrivi a casa vostra pronto da suonare. La finitura del mobile è di alta qualità con un noce con bella venatura e farà bella figura in ogni ambiente.",
      featured: true
    },
    {
      id: 2,
      model: "Pianoforte SEILER",
      color: "Noce",
      colorCode: "#A0522D",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1983",
      dimensions: {
        height: "112 cm",
        length: "211 cm",
      },
      price: "3.980",
      description: "La ben nota casa SEILER (ancora esistente) era conosciuta per la qualità dei suoi pianoforti.Ricordo ancora quando i signori SEILER ci invitarono a Kitzingen per visitare la fabbrica e ci offrirono una cena in casa loro. Fu una giornata emozionante! Questo modello è il più piccolo della gamma, con 112 cm. di altezza ed è proprio interessante osservare come la maestria dei costruttori tedeschi riesca a ricavare ottime sonorità anche da modelli compatti.Infatti la timbrica è molto piena e corposa anche nella regione bassa che, di solito, rimane penalizzata dal breve sviluppo delle corde.Come tutti i pianoforti SEILER monta la meccanica RENNER garanzia di precisione del tocco e di prontezza della ripetizione oltreché di durata e resistenza all’usura.  Questo esemplare fu costruito nel 1983 ed ha quindi giusti quarant’anni. È però sorprendente vedere come sia stato suonato così poco da lasciare i martelletti intonsi come anche tutte le parti in movimento come feltri e guarnizioni.Abbiamo dovuto solo fare una leggera registrazione della meccanica per ovviare al lungo periodo di inattività.Si tratta quindi di un pianoforte ancora tutto da sfruttare che potrà accompagnare lo studente dai primi anni fino anche all’accesso in Conservatorio quando sarà preferibile passare a un mezza coda.Oppure potrà dare grandi soddisfazioni anche al semplice amatore.",
      featured: true
    },
    {
      id: 3,
      model: "Carl Hardt Stuttgart",
      color: "Nero",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Restaurato",
      productionDate: "NaN",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "3.950",
      description: "Questo esemplare è stato ristrutturato interamente con sostituzione non solo delle caviglie ma anche del somiere che era crepato compromettendo la tenuta dell’accordatura.I martelletti invece sono i suoi originali ancora in ottimo stato a testimoniare il poco utilizzo a cui è stato sottoposto. Ora è dotato di ottima sonorità con bassi pieni e potenti degni di un’ottima marca tedesca.La ristrutturazione di cui ha beneficiato gli consente di iniziare una nuova vita ed essere suonato ancora per altri cinquant’anni.",
      featured: true
    },
    {
      id: 4,
      model: "SAUTER 108",
      color: "Noce",
      colorCode: "#8B5A2B",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1975",
      dimensions: {
        height: "108 cm",
        length: "NaN cm",
      },
      price: "2.480",
      description: "La casa SAUTER è stata fondata nel 1819 a SPAICHINGEN ed è quindi una delle più antiche fabbriche di pianoforti della Germania e una delle poche ancora in attività, costruttrice anche dei pianoforti a marchio KRAUSS.Questo esemplare è stato venduto nuovo da noi nel 1975 e il cliente lo ha suonato per alcuni anni fino al 1982 per poi essere lasciato inutilizzato. La meccanica RENNER conferisce alla tastiera un tocco giustamente resistente e una ripetizione pronta mentre la sonorità è ottima anche nella regione bassa. Possiamo ben apprezzare la maestria dei costruttori tedeschi che riescono a ricavare una timbrica piena anche da un pianoforte di statura contenuta come questo 108.Abbiamo eseguito una manutenzione ordinaria ai martelletti e alla meccanica nonché regolato l’affondo della tastiera mentre l’ultima accordatura verrà eseguita prima della consegna in modo che possa arrivare a casa vostra pronto da suonare. Questo esemplare potrà seguire lo studente dai primi anni fino anche all’accesso in Conservatorio quando sarà preferibile passare a un mezza coda.Oppure potrà dare grandi soddisfazioni anche al semplice amatore.",
      featured: true
    },
    {
      id: 5,
      model: "SCHIMMEL 116 (silent)",
      color: "Noce",
      colorCode: "#954A2C",
      type: "Verticale",
      condition: "Come nuovo",
      productionDate: "2008",
      dimensions: {
        height: "116 cm",
        length: "NaN cm",
      },
      price: "8.950",
      description: "Questo pianoforte ha una storia singolare:14 anni fa una nostra cliente che aveva già acquistato da noi un pianoforte alcuni anni prima, desiderando sostituirlo con uno di ottima qualità, tornò da noi e scelse questo modello Schimmel poiché rimase colpita dal suo suono ricco e potente.Essendo però già in lite con il vicino del piano di sopra dedito ad attività “rumorose”, preferì fosse dotato di sistema di silenziamento. Scelse, inoltre, una tinta in noce chiaro che si adattasse alla sua sala, cosicché dovemmo ordinarlo appositamente con silenziamento già montato in fabbrica.Lo consegnammo il 15 aprile 2008 e, subito, provò a suonare per qualche giorno ma le ripicche con il vicino “rumoroso”ripresero immediatamente mentre suonare con il silenziamento inserito non le dava soddisfazione.Fu così che suonò solo per pochi giorni e poi lo coprì con un drappo per proteggerlo dalla luce e lo tenne fino a oggi senza più toccarlo.Ora si trova da noi presentandosi senza neppure un graffietto e in perfetto stato”PARI AL NUOVO”di dentro e di fuori.Chi avrà la fortuna di poterselo assicurare potrà godere non solo del suo bellissimo suono brillante e ricco di armoniche, ma anche di un pianoforte intonso e ancora tutto da sfruttare.",
      featured: true
    },
    {
      id: 6,
      model: "Pianoforte SCHIEDMAYER",
      color: "Noce",
      colorCode: "#8B5A2B",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1972",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "2.980",
      description: "Schiedmayer è uno dei più grandi nomi della storia del pianoforte, stabilmente nell’Olimpo dei 5/6 migliori marchi.Ancora oggi questi pianoforti riescono a emozionare per la ricchezza di suono e la dolcezza timbrica ormai persa nei suoni di oggi.Questo esemplare è stato acquistato nuovo del 1972 nel periodo in cui Schiedmayer  costruiva pochi esemplari con la massima cura… I martelletti sono ancora i suoi originali a testimonianza di quanto poco sia stato suonato in questi cinquant’anni e potrà ancora deliziare il suo fortunato proprietario per altri cinquanta. È stata sufficiente una ordinaria revisione della meccanica per ovviare ai lunghi anni di inutilizzo e riportarlo alla sua originaria efficienza.Un pianoforte di questa levatura potrà accompagnare lo studente anche nolo studio avanzato.La finitura molto accurata con perfetto allineamento delle venature in noce nobiliterà l’ambiente in cui verrà collocato.",
      featured: true
    },
    {
      id: 7,
      model: "ZIMMERMANN S6 126",
      color: "Nero lucido",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Nuovo",
      productionDate: "NaN",
      dimensions: {
        height: "126 cm",
        length: "NaN cm",
      },
      price: "7.070",
      description: "La Casa ZIMMERMANN è uno dei più vecchi e blasonati costruttori di pianoforti tedeschi che, dopo la riunificazione delle due Germanie, entrò a far parte  del gruppo BECHSTEIN. Tutti i modelli sono stati riprogettati dal Centro Ricerca e Sviluppo BECHSTEIN di Seifhennersdorf in Sassonia e ora vengono costruiti in oriente sotto il diretto controllo dei tecnici BECHSTEIN e rispettando i criteri BECHSTEIN.Non si deve pensare che, essendo i pianoforti ZIMMERMANN a prezzo accessibile, si sia voluto risparmiare sulla qualità dei materiali o sulla precisione della lavorazione.Inoltre quando escono dalla fabbrica vengono inviati in Germania dove, nello stabilimento di Seifhennersdorf, subiscono il controllo qualità di tutto il montaggio e delle rifiniture prima di venire inviati ai concessionari di tutta Europa.In definitiva possiamo dire che i pianoforti ZIMMERMANN conciliano la qualità tedesca con un prezzo orientale.Il modello S6 di 126  cm è dotato di una voce poderosa e di una tastiera con la giusta pesatura atta a condurre lo studente verso gli esami di Conservatorio.",
      featured: true
    },
    {
      id: 8,
      model: "W.HOFFMANN V 131",
      color: "Nero lucido",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Nuovo",
      productionDate: "NaN",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "12.800",
      description: "W.HOFFMANN è uno dei più celebri nomi fra i costruttori di pianoforti tedeschi che costruiva anche per altri marchi come Euterpe, Feurich, e Seiler (per le code).Nel 1992l’attività fu rilevata da BECHSTEIN che trasferì la produzione a Hradec Kralove in Repubblica Ceca nello stabilimento ex Bohemia appositamente acquistato e rimodernato costituendo quindi la C.BECHSTEIN EUROPE cioè il suo secondo polo produttivo europeo e, giova ricordare, che si tratta del più importante gruppo produttore di pianoforti in Europa. Tutti i modelli sia verticali che a coda sono stati riprogettati secondo le direttive del centro ricerca e sviluppo BECHSTEIN di Seifhennersdorf in Sassonia e la produzione è stata riorganizzata con l’introduzione di macchine a controllo numerico per la fabbricazione  di tutti i componenti in modo da garantire uniformità di produzione per eliminare le differenze qualitative da un esemplare all’altro.Il montaggio di tutte le parti viene poi affidato a tecnici con esperienza che assicurano la cura artigianale indispensabile per ottenere lo standard qualitativo BECHSTEIN.La meccanica originale HOFFMANN, anch’essa progettata dal centro ricerca e sviluppo di Seifhennersdorf, assicura la perfetta trasmissione del movimento fino al martelletto ottenendo le sfumature timbriche che il tocco del pianista gli ha impresso.I martelletti sono fabbricati da BECHSTEIN nello stabilimento di Seifhennersdorf onde avere la certezza che siano conformi  alle specifiche  richieste dal centro ricerca e sviluppo mentre la tavola armonica subisce un trattamento che la rende resistente agli sbalzi climatici quindi da evitare la formazione di crepe.Tutti gli accorgimenti sopra descritti sono finalizzati a ottenere la lunga durata del pianoforte che potrà venire tramandato per generazioni.Ma non è tutto:il tratto saliente dei pianoforti W.HOFFMANN è la sonorità di stampo centro europeo con una timbrica ricca di armoniche e un’ampia possibilità di escursione dinamica con pianissimi limpidi e fortissimi molto pieni.Questo esemplare è espressamente indirizzato agli studenti che non potendo, per motivi di spazio, servirsi della coda riusciranno ugualmente a preparare gli esami su uno strumento adeguato.",
      featured: true
    },
    {
      id: 9,
      model: "SCHIEDMAYER 3/4",
      color: "Palissandro",
      colorCode: "#6a503f",
      type: "Coda",
      condition: "Restaurato",
      productionDate: "1906",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "29.850",
      description: "SCHIEDMAYER:uno dei due o tre marchi più prestigiosi di tutta la storia del pianoforte.Per questo abbiamo deciso di eseguire un restauro maniacale onde riportarlo al suo splendore e alla sua efficienza.Questo esemplare è stato costruito nel 1906/1907.Quando lo abbiamo ricevuto non si presentava tanto bene:era nero e con molte crepe nella tavola armonica, Abbiamo raschiato la vernice nera in un angolino scoprendo un bel palissandro. Evidentemente uno dei suoi precedenti proprietari lo aveva preferito nero.Per riparare le crepe sulla tavola si doveva disarmare il telaio di ghisa.A questo punto abbiamo pensato che sarebbe stato bello restituirgli tutta la vigoria del suo suono originale. Abbiamo preferito seguire la strada più difficile.Certo sarebbe stato più facile farci fare una tavola nuova.Ma la tavola armonica è il cuore del suono e avremmo perso la sua originalità.Così abbiamo smontato la tavola pezzo per pezzo rimontandola  con particolare attenzione all’incollaggio delle catene affinché riprendesse la sua curvatura e siamo molto soddisfatti del risultato finale.Siamo stati in dubbio sulla martelliera che non era ancora del tutto consumata ma, pensandoci bene, puntando al massimo risultato, abbiamo scelto una bella martelliera nuova.Adesso può sfidare, sul piano delle prestazioni, i pianoforti nuovi delle grandi marche. In tanti anni non ho mai sentito un pianoforte d’epoca suonare così e possiamo ben dire che suona adesso come quando era nuovo, forse persino meglio(la tavola stagionata per cent’anni è più leggera e vibra meglio).Avremmo potuto riverniciare il telaio di ghisa ma abbiamo preferito conservare la sua originalità lasciandolo come era. Infine, abbiamo poi deciso di sverniciarlo completamente perché si presentasse di nuovo nel suo palissandro originale.Attualmente lo stiamo utilizzando per servizio concerti con grande soddisfazione dei pianisti. La stessa soddisfazione che ne potrà ricavare il suo fortunato acquirente. Questo esemplare si presta non solo a utilizzo studio in casa privata ma anche per rappresentanza in ville, castelli, hotel, ecc",
      featured: true
    },
    {
      id: 10,
      model: "Pianoforte BECHSTEIN",
      color: "Palissandro",
      colorCode: "#6a503f",
      type: "Verticale",
      condition: "Restaurato",
      productionDate: "1876",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "6.500",
      description: "La casa BECHSTEIN non ha bisogno di presentazioni essendo una delle più blasonate case produttrici di pianoforti di altissima qualità.Questo esemplare, costruito nel 1876 è testimone di come la qualità venga fuori alla distanza. Le caviglie erano leggermente allentate e abbiamo preferito sostituirle per una sicura tenuta dell’accordatura. I martelletti erano i suoi originali ma, dopo 145 anni erano consumati ed è stato necessario inviarli in Germania per ottenere una feltratura nuova rispettandone l’originalità. Mentre le smorze sono state sostituite. Parimenti la meccanica è stata interamente revisionata onde consentire un tocco preciso e sicuro. Desidero sottolineare la straordinaria bellezza del mobile in Palissandro Rio, il più pregiato, che oggi sarebbe impossibile ricostruire non solo per i costi proibitivi ma anche perché il palissandro rientra fra le specie protette e quindi contingentate. La sonorità riflette l’epoca in cui era stato costruito privilegiando la dolcezza. Si tratta di un esemplare di eccezionale valore storico che andrà a impreziosire l’ambiente in cui verrà collocato.Giova anche ricordare che il modello alto costruito oggi da Bechstein, non certo in palissandro ma in nero lineare costa oltre 51.000 euro. Abbiamo iniziato il restauro smontando la meccanica, la tastiera e le caviglie che abbiamo sostituito con caviglie nuove mentre sono apparse alcune crepe sulla tavola armonica che abbiamo riparato ridando anche un po’ di curvatura alla tavola. Appena arrivata la nuova martelliera dalla Germania abbiamo iniziato il rimontaggio della meccanica proseguendo con sostituzione delle smorze e registrazione completa della meccanica.Nel frattempo proseguiva la verniciatura, naturalmente a stoppino, come era stata fatta in origine.",
      featured: true
    },
    {
      id: 11,
      model: "Steinway&Sons 3/4 mod. C",
      color: "Palissandro",
      colorCode: "#503f2b",
      type: "Coda",
      condition: "Restaurato",
      productionDate: "1884",
      dimensions: {
        height: "NaN cm",
        length: "227 cm",
      },
      price: "15.000",
      description: "Magnifico STEINWAY E SONS modello C cm 227 num. di matricola 52.402 è stato fabbricato nel 1.884 circa ed è in forma smagliante a riprova di quanto alta sia la qualità di questa marca e quanto meritata la sua fama. La tastiera di 85 tasti è in avorio ed ha un tocco consistente come tutti gli Steinway di quel periodo e poiché la sua martelliera originale era consumata abbiamo preferito sostituirla con una martelliera adeguata al suo rango. Il modello C è un vero e proprio pianoforte da concerto per musica da camera o per piccoli teatri.Farebbe magnifica figura nella hall di un albergo come in una spaziosa salotto e è il vostro compagno che vi aiuterà a rilassarvi nei momenti liberi. Naturalmente è anche un qualificato compagno di studi per chi dovesse ancora presentarsi agli esami del diploma. Inoltre rappresenterà un ottimo investimento dato che i pianoforti di questa marca sono eterni e mantengono il valore nel tempo.",
      featured: true
    },
    {
      id: 12,
      model: "Pianoforte TALLONE 1/2",
      color: "Mogano",
      colorCode: "#6B4423",
      type: "Coda",
      condition: "Usato",
      productionDate: "1968",
      dimensions: {
        height: "NaN cm",
        length: "180 cm",
      },
      price: "13.980",
      description: "Cesare Augusto Tallone è stato uno dei migliori costruttori di pianoforti al mondo.La crescita della sua notorietà mondiale si ebbe negli anni ’60 come accordatore di fiducia al seguito di BENEDETTI MICHELANGELI. Proprio durante una turnee del maestro in Giappone la perfettra preparazione del pianoforte non sfuggì ai tecnici giapponesi della Yamaha e Cesare Augusto fu invitato a visitare la fabbrica dove fu accolto dal presidente della YAMAHA in persona. In quell’occasione gli fu commissionato un 3/4 coda la cui alta qualità fu considerata a tal punto che la Yamaha lo incaricò della costruzione di un pianoforte gran coda da concerto a cui Cesare Augusto potè sovrintendere presso la Yamaha stessa.In seguito rimase ancora a lungo consulente presso la casa Yamaha. Questo esemplare è un mezza coda di 180 cm. fabbricato nel 1968/69 e sempre rimasto in casa privata dove Il sig. Tallone veniva ad eseguire le accordature.La finitura è in un bellissimo mogano di tonalità molto calda mentre la cura maniacale del dettaglio che Tallone profondeva nei suoi pianoforti si nota nella fusione della ghisa come nella linea del leggio ed in ogni particolare.Naturalmente la tastiera è in avorio mentre la meccanica è una Schwander di Parigi.Dallo spessore dei martelletti si nota come in questi cinquant’anni sia stato suonato davvero poco, tanto che è stata sufficiente un’accurata registrazione della meccanica ed una attenta intonazione della martelliera per riportarlo al suo suono originale.",
      featured: true
    },
    {
      id: 13,
      model: "BALDWIN 115",
      color: "Noce",
      colorCode: "#9b4e0a",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1970",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "1.680",
      description: "BALDWIN da sempre uno dei pianoforti americani più famosi utilizzato da molti pianisti per concerti e registrazioni.Innumerevoli colonne sonore di famosi film sono state registrate con pianoforti BALDWIN.Negli anni ’70 la casa Baldwin aveva allestito tre modelli che si adattassero ai gusti europei e questo era il migliore della serie.Proviene da casa privata dove era stato suonato per alcuni anni per poi essere lasciato in disparte.Ora dovendo traslocare la proprietaria mi ha pregato di occuparmene.Abbiamo revisionato la meccanica per sciogliere i movimenti che si erano impigriti nei lunghi anni di inutilizzo e prima della consegna verrà accordato un’ultima volta in modo che arrivi a casa vostra pronto da suonare.",
      featured: true
    },
    {
      id: 14,
      model: "Shulze Pollmann Antik",
      color: "nan",
      colorCode: "#9b4e0a",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1985",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "1.980",
      description: "I due fabbricanti di pianoforti Shulze e Pollmann che avevano sede in Torino decisero,prima della guerra, di riunire le loro due fabbriche a Bolzano creando la Fabbriche riunite di pianoforti Schulze Pollmann. Questo esemplare fu da noi venduto nuovo circa quarant’anni fa e suonato per alcuni anni per poi venire lasciato inutilizzato fino ai giorni nostri.Ora,dovendo trasfrirsi in una casa più piccola,mi hanno chiamato pregandomi di occuparmene.Il modello Antik era intermedio nella gamma Schulze Pollmann e montava la meccanica Renner,garanzia di pronta ripetizione e lunga durata.L’altezza di 115 cm. consente di ottenere una buona sonorità anche nella regione bassa e la dinamica del tasto si presta anche ad uno studio avanzato fino agli esami di Conservatorio.",
      featured: true
    },
    {
      id: 15,
      model: "STEINERT 121",
      color: "Noce",
      colorCode: "#9b4e0a",
      type: "Verticale",
      condition: "Usato",
      productionDate: "2000",
      dimensions: {
        height: "121 cm",
        length: "NaN cm",
      },
      price: "2.500",
      description: "I pianoforti STEINERT venivano costruiti a Torino da un artigiano,ancora in vita,che ha però cessato la produzione una ventina di anni fa.Questo modello 121 è uno degli ultimi costruiti ed essendo alto 121 è anche dotato di buona sonorità soprattutto nei bassi. La meccanica RENNER conferisce alla tastiera la giusta resistenza al tocco e una pronta ripetizione atta all’apprendimento della tecnica della mano.Inotre il mobile in noce è dotato di belle venature che gli conferiscono un aspetto elegante.proviene da una casa privata dove era stato inutilizzato negli ultimi vent’anni e,di conseguenza,abbiamo registrato la meccanica e controllato l’affondo della tastiera e,naturalmente,lo abbiamo accordato. Inoltre un’ultima accordatura verrà eseguita prima della consegna in modo che arrivi a casa vostra pronto da suonare.",
      featured: true
    },
    {
      id: 16,
      model: "YAMAHA C3",
      color: "Nero",
      colorCode: "#000000",
      type: "Coda",
      condition: "Usato",
      productionDate: "1982",
      dimensions: {
        height: "NaN cm",
        length: "186 cm",
      },
      price: "10.980",
      description: "Il Pianoforte YAMAHA C3 è talmente conosciuto da non avere bisogno di presentazione.Ormai divenuto uno standard per aule di Conservatorio come per concerti.Questo esemplare è stato acquistato nuovo nel 1982. Ha quindi quarant’anni ma è stato suonato ben poco.Infatti la proprietaria lo aveva acquistato quando frequentava il terzo anno di Conservatorio e lo ha suonato fino al sesto anno quando ha dovuto lasciare per concentrarsi sullo studio del liceo. così è rimasto inutilizzato fino ad oggi. Adesso,dovendo riordinare l’arredamento, mi ha pregato di occuparmene.I martelletti sono in ottime condizioni,a riprova dello scarso utilizzo a cui è stato sottoposto ed abbiamo solo eseguito una registrazione meccanica per riportarlo alla sua originaria prontezza. Potrà accompagnare lo studente nella preparazione degli esami di Conservatorio come tenere compagnia al semplice amatore.",
      featured: true
    },
    {
      id: 17,
      model: "YAMAHA G3",
      color: "Nero",
      colorCode: "#000000",
      type: "Coda",
      condition: "Usato",
      productionDate: "1974",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "6.980",
      description: "Questo esemplare è stato costruito nel 1974 ed ha quindi esattamente cinquant’anni.Era stato acquistato,già usato, da un nostro cliente,bravissimo pianista ma già anziano,circa vent’anni fa.Ora non essendoci più lui,la figlia mi ha chiesto di occuparmene.Abbiamo visto che i martelletti erano piuttosto consumati(cosa normale per un pianoforte di cinquant’anni) ed abbiamo deciso di mandare la martelliera in Germania da dove è tornato con una bella feltratura nuova.Abbiamo inoltre registrato tutta la meccanica riportandola alle sue regolazioni originali.Ora è pronto per affrontare una nuova vita ed accompagnare lo studente di Conservatorio fino agli esami od anche per allietare le ore libere del semplice amatore.",
      featured: true
    },
    {
      id: 18,
      model: "KAWAI KG2",
      color: "Nero",
      colorCode: "#000000",
      type: "Coda",
      condition: "Usato",
      productionDate: "1987",
      dimensions: {
        height: "NaN cm",
        length: "174 cm",
      },
      price: "8.700",
      description: "Il Pianoforte KAWAI KG2 è un caposaldo della produzione di questa ben nota casa giapponese tanto da essere stato in alcuni anni il modello di pianoforte a coda più venduto nel mondo.I motivi di questo grande successo sono parecchi:innanzitutto la misura di 174 cm. che gli consente di essere inserito in una normale camera. In seconda istanza la sonorità che riesce a sprigionare ci indurrebbe a credere di essere in presenza di un modello di maggiori dimensioni.Un altro punto di forza è la qualità costruttiva giapponese ormai riconosciuta come di grande affidabilità che contribuisce a rendere la tastiera scorrevole e con una ripetizione molto precisa.A tutte queste qualità si va ad aggiungere anche un prezzo molto accessibile.Questo esemplare porta il numero 1686649 ed è perciò stato fabbricato nel 1987 ed era stato acquistato per una ragazza che studiava il pianoforte al Conservatorio e che ha studiato per alcuni anni dedicandosi poi ad altre attività.Ora,dovendo traslocare in una casa più piccola e non suonandolo più da molti anni mi ha pregato di occuparmene.Abbiamo registrato bene la meccanica e ripristinato le regolazioni corrette che si erano alterate nei molti anni di inattività.I martelletti sono ancora in ottimo stato a testimonianza di quanto poco sia stato suonato nei suoi primi 35 anni.Ora è pronto per iniziare la sua seconda vita.",
      featured: true
    },
    {
      id: 19,
      model: "BECHSTEIN 1/2 coda",
      color: "Nero",
      colorCode: "#000000",
      type: "Coda",
      condition: "Usato",
      productionDate: "1903",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "4.500",
      description: "Questo esemplare è stato fabbricato nel 1903 ed ha beneficiato di un radicale restauro alcuni anni fa. Infatti era stata completamente revisionata la meccanica con sostituzione di martelletti e smorze nonchè di feltri e pelli. Inoltre era stata riparata la tavola armonica che presentava alcune crepe ed erano state sostituite le caviglie. Anche il mobile era stato completamente riverniciato. Il risultato è soddisfacente sviluppando una sonorità potente su tutto l’arco della tastiera. Tiene benissimo l’accordatura  ma,purtroppo, recentemente si sono aperte alcune crepe nel somiere nella regione dei bassi (come si vede dalla foto) e bisognerà pensare che,o prima o dopo,il somiere andrà sostituito con una spesa quantificabile i 6/7000 euro. Per questo motivo il prezzo attuale è così basso.",
      featured: true
    },
    {
      id: 20,
      model: "SAUTER 113",
      color: "Noce",
      colorCode: "#9b4e0a",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1819",
      dimensions: {
        height: "113 cm",
        length: "NaN cm",
      },
      price: "2.780",
      description: "Risale al 1819 la fondazione della fabbrica di pianoforti SAUTER che credo sia la più antica fra le fabbriche di pianoforti ancora in attività.Questo modello 113 è dotato di grande sonorità nonostante la statura contenuta.Infatti ascoltandolo suonare sembrerebbe un modello di maggiore altezza.Naturalmente la meccanica RENNER gli conferisce il tocco con la giusta pesatura e la pronta ripetizione che favoriscono l’apprendimento della tecnica della mano.La ricchezza timbrica tipica dei pianoforti tedeschi,completa il quadro di qualità di questo esemplare.",
      featured: true
    },
    {
      id: 21,
      model: "Pianoforte MORRISON",
      color: "Mogano",
      colorCode: "#6B4423",
      type: "Verticale",
      condition: "Usato",
      productionDate: "NaN",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "990",
      description: "Si tratta di un pianoforte di fabbricazione orientale dotato di una meccanica che conferisce alla tastiera la giusta pesatura per il corretto apprendimento della tecnica della mano.Anche la prontezza della ripetizione contribuisce a facilitare lo studio del principiante che si troverà a progredire rapidamente.Si tratta di un esemplare adatto sia allo studio sia a chi voglia semplicemente suonare per diletto.",
      featured: true
    },
    {
      id: 22,
      model: "BECHSTEIN mod. 7",
      color: "Nero",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Usato",
      productionDate: "1934",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "2.480",
      description: "Il modello 7 è stato per molti anni il modello di punta fra i pianoforti verticali della BECHSTEIN poi sostituito dal mod. 8 che è a tutt’oggi in produzione.Questo esemplare è stato costruito nel 1934 ed è alto 137 cm.Quindi la lunghezza delle corde e l’ampiezza della tavola armonica sono pari ad un 1/2 coda come si sente dalla profondità e pienezza del suono specie nella regione dei bassi.La sonorità è molto piena come si usava all’epoca e la robustezza della costruzione tipica di questa marca ci assicura ancora una lunga vita.",
      featured: true
    },
    {
      id: 23,
      model: "KAPS 1/2 coda",
      color: "Nero",
      colorCode: "#000000",
      type: "Coda",
      condition: "Usato",
      productionDate: "1908",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "4.350",
      description: "Questo pianoforte misura 185 cm. e si colloca quindi nella categoria dei pianoforti professionali che,grazie alle misure abbastanza contenute,riescono a trovare spazio anche in un salotto.Questo esemplare è stato fabbricato nel 1908 ed è appena stato restaurato nelle parti vitali con riparazione delle crepe della tavola armonica,sostituzione caviglie,martelletti e smorze.in modo da dare una completa garanzia per i prossimi cinquant’anni.Può quindi essere utilizzato sia dallo studente di pianoforte che dal semplice amatore che voglia rilassarsi suonando nei momenti liberi.",
      featured: true
    },
    {
      id: 24,
      model: "Pianoforte A.GRAND BERLIN",
      color: "Nero",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Usato",
      productionDate: "NaN",
      dimensions: {
        height: "NaN cm",
        length: "NaN cm",
      },
      price: "1.750",
      description: "Questo esemplare di pianoforte marca A.GRAND Berlin è naturalmente fabbricato in Germania e monta la meccanica RENNER garanzia di qualità e durata oltre alla giusta pesatura della tastiera e prontezza della ripetizione. Sono proprio le caratteristiche necessarie allo studio per il corretto apprendimento della tecnica della mano.Si tratta perciò di un modello ideale per principianti che potranno essere accompagnati fino al quinto/sesto anno di Conservatorio oltre i quali verrà consigliato un mezza coda od almeno un verticale più alto e professionale.Potrà parimenti accompagnare anche il semplice amatore che si diletterà a suonare nei momenti liberi.Naturalmente è stato da noi completamente revisionato per riportarlo alla completa efficienza dopo i lunghi anni di inutilizzo e verrà consegnato a casa vostra appena accordato e pronto da suonare.Naturalmente è stato da noi completamente revisionato per riportarlo alla completa efficienza dopo i lunghi anni di inutilizzo e verrà consegnato a casa vostra appena accordato e pronto da suonare.",
      featured: true
    },
    {
      id: 25,
      model: "YAMAHA U3",
      color: "Nero",
      colorCode: "#000000",
      type: "Verticale",
      condition: "Nuovo",
      productionDate: "1983",
      dimensions: {
        height: "110 cm",
        length: "NaN cm",
      },
      price: "2.750",
      description: "Il modello U3 della YAMAHA è un classico senza tempo.L’ampiezza della tavola armonica e la lunghezza delle corde gli consentono di sviluppare una sonorità da piccolo coda mentre la tastiera,con qualche grammo in più di pesatura rispetto ai modelli più piccoli,unitamente alla proverbiale prontezza e precisione della meccanica YAMAHA,,lo rende adatto anche alla preparazione degli esami di Conservatorio per chi non abbia la possibilità di servirsi di un mezza coda.Questo esemplare è stato fabbricato nel 1983 ed è arrivato adesso dal Giappone dove ha beneficiato di una completa ristrutturazione,eseguita in fabbrica, con sostituzione di tutte le parti usurate come martelletti,smorze,feltri,pelli,guarnizioni ma anche di parti non usurate ottenendo quindi lo status di PARI AL NUOVO. Ora è pronto per affrontare una nuova vita ed accompagnare lo studente fino agli esami di Conservatorio.",
      featured: true
    },
    {
      id: 26,
      model: "HERMANN 112",
      color: "Bianco",
      colorCode: "#ffffff",
      type: "Verticale",
      condition: "Nuovo",
      productionDate: "2024",
      dimensions: {
        height: "112 cm",
        length: "NaN cm",
      },
      price: "3.980",
      description: "Questo modello di HERMANN è stato progettato da KLAUS FENNER il più famoso dei maestri costruttori di pianoforti tedesco ed il risultato non delude:sonorità uniforme su tutto l’arco della tastiera e piena anche nei bassi nonostante l’altezza contenuta ed una tastiera con la giusta resistenza al tocco ed una prontezza di ripetizione che facilita l’apprendimento della tecnica della mano.Si tratta di un modello adattissimo al principiante come anche allo studente già un pò più avanzato che potrà essere accompagnato fino al quinto/sesto anno quando è consigliabile passare al mezza coda.",
      featured: true
    }
  ];

export default pianos;
